### ISSUE TITLE
Shadowing of functions or modules

### ISSUE THREAD

**Issue by MinionJakub** [fram-lang/dbl#169] opened 2024-12-17 14:53 UTC
During correcting the red black tree due to new features, I encountered types for List.append where shadowed. The simplified version of this problem with my short investigation:
```
import open Base/Assert
import List

let x = [1,2,3]
let y = [4,5,6]

let z = List.append x y

{#
# Error is only if this file exist in the lib folder. 
# Outside of lib folder it doesn't produce error.
# For error occurrence all of imports are needed. 
# More testing needed for determining whether 
# it's much larger problem with modules and installed libraries.
#}
```

**Comment by forell** [comment] 2024-12-22 20:30
This problem requires somewhat unusual conditions to reproduce: this file has to be evaluated as a non-library program (for example by passing it as an argument to `dbl`) while being placed in the library directory. This is because the current implementation of imports assumes that the hierarchy for the standard library and the program are separate. This is clearly not going to be too much of a problem in practice, so I'm not too pressed about fixing it in DBL, though we could make the future Fram compiler more robust once it's time to implement file support there. Since you marked this as `wontfix` already, I'll just close the issue for now.

**Closed** 2024-12-22 20:31 UTC
Labels: bug, wontfix, stdlib
